-- MySQL Script generated by MySQL Workbench
-- Tue Sep 23 23:35:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Billetera_virtual
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Billetera_virtual` ;

-- -----------------------------------------------------
-- Schema Billetera_virtual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Billetera_virtual` DEFAULT CHARACTER SET utf8 ;
USE `Billetera_virtual` ;

-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Usuarios` (
  `ID_Usuarios` INT NOT NULL,
  `Nombre_Usuario` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Hash_Password` VARCHAR(45) NOT NULL,
  `Pin_Seguridad` VARCHAR(45) NOT NULL,
  `Fecha_Registro` DATETIME NOT NULL,
  `Estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_Usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Contratos_Inteligentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Contratos_Inteligentes` (
  `ID_Contratos_Inteligentes` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Codigo_smart_contract` VARCHAR(45) NOT NULL,
  `Fecha_creacion` DATETIME NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Contratos_Inteligentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Billetaras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Billetaras` (
  `ID_Billetera` INT NOT NULL,
  `Moneda` CHAR(3) NOT NULL,
  `Saldo` FLOAT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `direccion_blockchain` VARCHAR(45) NOT NULL,
  `Auteticaciones_ID_Auteticacion` INT NOT NULL,
  `Transacciones_ID_Transaccion` INT NOT NULL,
  `Contratos_Inteligentes_ID_Contratos_Inteligentes` INT NOT NULL,
  `Usuarios_ID_Usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_Billetera`, `Auteticaciones_ID_Auteticacion`, `Transacciones_ID_Transaccion`, `Contratos_Inteligentes_ID_Contratos_Inteligentes`, `Usuarios_ID_Usuarios`),
  CONSTRAINT `fk_Billetaras_Contratos_Inteligentes1`
    FOREIGN KEY (`Contratos_Inteligentes_ID_Contratos_Inteligentes`)
    REFERENCES `Billetera_virtual`.`Contratos_Inteligentes` (`ID_Contratos_Inteligentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Billetaras_Usuarios1`
    FOREIGN KEY (`Usuarios_ID_Usuarios`)
    REFERENCES `Billetera_virtual`.`Usuarios` (`ID_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Billetaras_Contratos_Inteligentes1_idx` ON `Billetera_virtual`.`Billetaras` (`Contratos_Inteligentes_ID_Contratos_Inteligentes` ASC) VISIBLE;

CREATE INDEX `fk_Billetaras_Usuarios1_idx` ON `Billetera_virtual`.`Billetaras` (`Usuarios_ID_Usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Notificaciones` (
  `ID_Notificacion` INT NOT NULL,
  `Tipo_Notificacion` VARCHAR(45) NOT NULL,
  `Mensaje_Notificacion` VARCHAR(45) NOT NULL,
  `Fecha_Envio` DATETIME NOT NULL,
  `Estado_Notificacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Notificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Transacciones` (
  `ID_Transaccion` INT NOT NULL,
  `Tipo_Transaccion` VARCHAR(20) NOT NULL,
  `Monto_Transaccion` FLOAT NOT NULL,
  `Fecha_Transaccion` DATETIME NOT NULL,
  `Estado_Transaccion` VARCHAR(20) NOT NULL,
  `Hash_Blockchain` VARCHAR(255) NOT NULL,
  `Notificaciones_ID_Notificacion1` INT NOT NULL,
  `Billetaras_ID_Billetera` INT NOT NULL,
  `Billetaras_Auteticaciones_ID_Auteticacion` INT NOT NULL,
  `Billetaras_Transacciones_ID_Transaccion` INT NOT NULL,
  `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` INT NOT NULL,
  `Billetaras_Usuarios_ID_Usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_Transaccion`, `Notificaciones_ID_Notificacion1`, `Billetaras_ID_Billetera`, `Billetaras_Auteticaciones_ID_Auteticacion`, `Billetaras_Transacciones_ID_Transaccion`, `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes`, `Billetaras_Usuarios_ID_Usuarios`),
  CONSTRAINT `fk_Transacciones_Notificaciones1`
    FOREIGN KEY (`Notificaciones_ID_Notificacion1`)
    REFERENCES `Billetera_virtual`.`Notificaciones` (`ID_Notificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacciones_Billetaras1`
    FOREIGN KEY (`Billetaras_ID_Billetera` , `Billetaras_Auteticaciones_ID_Auteticacion` , `Billetaras_Transacciones_ID_Transaccion` , `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` , `Billetaras_Usuarios_ID_Usuarios`)
    REFERENCES `Billetera_virtual`.`Billetaras` (`ID_Billetera` , `Auteticaciones_ID_Auteticacion` , `Transacciones_ID_Transaccion` , `Contratos_Inteligentes_ID_Contratos_Inteligentes` , `Usuarios_ID_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Transacciones_Notificaciones1_idx` ON `Billetera_virtual`.`Transacciones` (`Notificaciones_ID_Notificacion1` ASC) VISIBLE;

CREATE INDEX `fk_Transacciones_Billetaras1_idx` ON `Billetera_virtual`.`Transacciones` (`Billetaras_ID_Billetera` ASC, `Billetaras_Auteticaciones_ID_Auteticacion` ASC, `Billetaras_Transacciones_ID_Transaccion` ASC, `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` ASC, `Billetaras_Usuarios_ID_Usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Autenticaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Autenticaciones` (
  `ID_Autenticacion` INT NOT NULL,
  `Tipo_Autenticacion` VARCHAR(50) NOT NULL,
  `Detalle_Auteticacion` VARCHAR(45) NOT NULL,
  `Fecha_Autenticacion` DATETIME NOT NULL,
  `Resultado_Autenticacion` VARCHAR(45) NOT NULL,
  `Billetaras_ID_Billetera` INT NOT NULL,
  `Billetaras_Auteticaciones_ID_Auteticacion` INT NOT NULL,
  `Billetaras_Transacciones_ID_Transaccion` INT NOT NULL,
  `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` INT NOT NULL,
  `Billetaras_Usuarios_ID_Usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_Autenticacion`, `Billetaras_ID_Billetera`, `Billetaras_Auteticaciones_ID_Auteticacion`, `Billetaras_Transacciones_ID_Transaccion`, `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes`, `Billetaras_Usuarios_ID_Usuarios`),
  CONSTRAINT `fk_Autenticaciones_Billetaras1`
    FOREIGN KEY (`Billetaras_ID_Billetera` , `Billetaras_Auteticaciones_ID_Auteticacion` , `Billetaras_Transacciones_ID_Transaccion` , `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` , `Billetaras_Usuarios_ID_Usuarios`)
    REFERENCES `Billetera_virtual`.`Billetaras` (`ID_Billetera` , `Auteticaciones_ID_Auteticacion` , `Transacciones_ID_Transaccion` , `Contratos_Inteligentes_ID_Contratos_Inteligentes` , `Usuarios_ID_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Autenticaciones_Billetaras1_idx` ON `Billetera_virtual`.`Autenticaciones` (`Billetaras_ID_Billetera` ASC, `Billetaras_Auteticaciones_ID_Auteticacion` ASC, `Billetaras_Transacciones_ID_Transaccion` ASC, `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` ASC, `Billetaras_Usuarios_ID_Usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Auteticaciones_has_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Auteticaciones_has_Usuarios` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Tarjetas_Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Tarjetas_Registro` (
  `ID_Tarjetas` INT NOT NULL,
  `Tipo_tarjeta` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Tarjetascol` VARCHAR(45) NULL,
  `Tipo_Identidad_ID_Tipo_Identidad` INT NOT NULL,
  `Billetaras_ID_Billetera` INT NOT NULL,
  `Billetaras_Auteticaciones_ID_Auteticacion` INT NOT NULL,
  `Billetaras_Transacciones_ID_Transaccion` INT NOT NULL,
  `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` INT NOT NULL,
  `Billetaras_Usuarios_ID_Usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_Tarjetas`, `Tipo_Identidad_ID_Tipo_Identidad`),
  CONSTRAINT `fk_Tarjetas_Registro_Billetaras1`
    FOREIGN KEY (`Billetaras_ID_Billetera` , `Billetaras_Auteticaciones_ID_Auteticacion` , `Billetaras_Transacciones_ID_Transaccion` , `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` , `Billetaras_Usuarios_ID_Usuarios`)
    REFERENCES `Billetera_virtual`.`Billetaras` (`ID_Billetera` , `Auteticaciones_ID_Auteticacion` , `Transacciones_ID_Transaccion` , `Contratos_Inteligentes_ID_Contratos_Inteligentes` , `Usuarios_ID_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tarjetas_Registro_Billetaras1_idx` ON `Billetera_virtual`.`Tarjetas_Registro` (`Billetaras_ID_Billetera` ASC, `Billetaras_Auteticaciones_ID_Auteticacion` ASC, `Billetaras_Transacciones_ID_Transaccion` ASC, `Billetaras_Contratos_Inteligentes_ID_Contratos_Inteligentes` ASC, `Billetaras_Usuarios_ID_Usuarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Billetera_virtual`.`Tipo_Identidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Billetera_virtual`.`Tipo_Identidad` (
  `ID_Tipo_Identidad` INT NOT NULL,
  `Tipo_Identidad` VARCHAR(45) NOT NULL,
  `Pais_Recidencia` VARCHAR(45) NOT NULL,
  `Tarjetas_Registro_ID_Tarjetas` INT NOT NULL,
  `Tarjetas_Registro_Tipo_Identidad_ID_Tipo_Identidad` INT NOT NULL,
  PRIMARY KEY (`ID_Tipo_Identidad`, `Tarjetas_Registro_ID_Tarjetas`, `Tarjetas_Registro_Tipo_Identidad_ID_Tipo_Identidad`),
  CONSTRAINT `fk_Tipo_Identidad_Tarjetas_Registro1`
    FOREIGN KEY (`Tarjetas_Registro_ID_Tarjetas` , `Tarjetas_Registro_Tipo_Identidad_ID_Tipo_Identidad`)
    REFERENCES `Billetera_virtual`.`Tarjetas_Registro` (`ID_Tarjetas` , `Tipo_Identidad_ID_Tipo_Identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tipo_Identidad_Tarjetas_Registro1_idx` ON `Billetera_virtual`.`Tipo_Identidad` (`Tarjetas_Registro_ID_Tarjetas` ASC, `Tarjetas_Registro_Tipo_Identidad_ID_Tipo_Identidad` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
